[workspace]
members = ["app", "rtl8720-sys", "rtl8720-wlan", "lwip-nal"]
exclude = ["rtl8720-cargo", "minihttp"]

# [build]
# target = "thumbv8m.main-none-eabihf"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
