#!/usr/bin/env bash
set -Eeuo pipefail
bindgen \
    c/inc/bindgen.h \
    --use-core \
    --with-derive-default \
    --impl-debug \
    --no-doc-comments \
    --no-layout-tests \
    --generate-block \
    --default-enum-style "consts" \
    --ctypes-prefix "ffi::ctypes" \
    --rust-target "nightly" \
    -o src/ffi/bindings.rs -- \
        "-I." \
        "-Ic/inc/" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/os/freertos" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/os/freertos/freertos_v10.2.0/Source/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/os/freertos/freertos_v10.2.0/Source/portable/GCC/ARM_CM33/non_secure" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/os/os_dep/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/os/customer_rtos" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/misc" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/network/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/at_cmd" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/platform" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/wifi" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/wifi/rtw_wpa_supplicant/src" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/api/wifi/rtw_wpa_supplicant/src/crypto" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/application" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/media/framework" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/example" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/example/wlan_fast_connect" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/mbed/api" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/mbed/hal" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/mbed/hal_ext" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/mbed/targets/hal/rtl8721d" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/lwip/lwip_v2.0.2/port/realtek/freertos" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/lwip/lwip_v2.0.2/src/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/lwip/lwip_v2.0.2/src/include/lwip" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/lwip/lwip_v2.0.2/port/realtek" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/test" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/cmsis" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/fwlib" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/misc" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/src/osdep" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/src/hci" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/ssl/ssl_ram_map/rom" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/utilities" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/video/v4l2/inc" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/media/rtp_codec" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/file_system/fatfs" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/file_system/fatfs/r0.10c/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/file_system/ftl" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/sdio/realtek/sdio_host/inc" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/audio" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/i2s" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/application/xmodem" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/mDNS" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/fwlib/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/swlib/string" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/app/monitor/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/soc/realtek/amebad/app/xmodem" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/ssl/mbedtls-2.4.0/include" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/board/amebad/lib" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/board/amebad/src" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/board/amebad/src/vendor_cmd" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/board/common/inc" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/example/bt_config" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/app" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/bluetooth/gap" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/bluetooth/profile" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/bluetooth/profile/client" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/bluetooth/profile/server" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/os" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/platform" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/inc/stack" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/src/app/ble_central_client" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/bluetooth/realtek/sdk/src/mcu/module/data_uart_cmd" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/ir/protocol" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/src/core/option" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/src/hal" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/drivers/wlan/realtek/src/hal/phydm" \
        "-Itarget/sdk/hardware/system/libameba/sdk/component/common/network/ssl/mbedtls-2.4.0/include" \
        "-Itarget/toolchain/lib/gcc/arm-none-eabi/6.5.0/include" \
        "-Itarget/toolchain/lib/gcc/arm-none-eabi/6.5.0/include-fixed" \
        "-Itarget/toolchain/arm-none-eabi/include" \
        "-DARDUINO_SDK" \
        "-DCONFIG_PLATFORM_8721D" \
        "-DCONFIG_USE_MBEDTLS_ROM_ALG" \
        "-DCONFIG_FUNCION_O0_OPTIMIZE" \
        "-DDM_ODM_SUPPORT_TYPE=32" \
        "-D__CMSIS_GCC_H" \
        "-D_TRUSTZONE_H_" \
        "-D_STRPROC_H_" \
        "-mthumb" \
        "-w"
