[package]
name = "cargo-rtl8720"
version = "0.1.0"
authors = ["Phil Proctor <philliptproctor@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
structopt = "0.3"
derive_more = "0.99"
lazy_static = "1.4"
anyhow = "1.0"
